### ISSUE TITLE
TopicExpert generate_queries The output is not displayed as described

### ISSUE THREAD

**Issue by fsqinghuayu** [stanford-oval/storm#137]
when i use TopicExpert to generate_queries;
queries = self.generate_queries(topic=topic, question=question).queries
I try to print queries and find that topic and question is included in the queries
From my understanding, only queries need to be entered into the next RM， without topic and question
I tried using gpt-4o-mini and Deepseek chat, and the results were the same

**Comment by shaoyijia** [comment]
> I try to print queries and find that topic and question is included in the queries

Could you provide an input-output example for this step to help us better understand the issue?

**Comment by Yucheng-Jiang** [comment]
We just updated the bug report issue template. Please follow the template to help us better assist debugging. Appreciated!

template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Report following things
1. Input topic name
2. All output files generated for this topic as a zip file.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment:**
 - OS: [e.g. iOS, Windows]
 - Browser [e.g. chrome, safari] if the bug report is UI problem

**Comment by Yucheng-Jiang** [comment]
[Reminder] Will close this issue if have no further questions by end of this week.
