### ISSUE TITLE
More info on human-ai collaboration mode

### ISSUE THREAD

**Issue by cfregly** [stanford-oval/storm#151]
Can you provide more information on how this will work?  As well as an expected data for this to launch?

Also, will you be open-sourcing the full (non-demo-light) UI?  or are you keeping that out of the open source in favor of demo-light?

Last related question:  Will the human-ai collaboration mode be added to the demo-light UI?  If so, when?

Thanks!  Great project.

**Comment by Yucheng-Jiang** [comment]
> Can you provide more information on how this will work? 

We just made twitter post [here](https://x.com/YuchengJiang0/status/1828814109930061965) and post arxiv paper [here](https://www.arxiv.org/pdf/2408.15232)

>  As well as an expected data for this to launch?

We plan to gradually roll out UI to public in the next few weeks

> Also, will you be open-sourcing the full (non-demo-light) UI?

Due to security and ongoing effort from our team, we don't plan to release full UI in the near future. We are happy to support any contribution to demo light (there is already a pretty [good one in progress](https://github.com/stanford-oval/storm/pull/135))

> Will the human-ai collaboration mode be added to the demo-light UI? If so, when?

We'll see how the project goes and potentially support this by our team or leave it to the open community.
